version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - db:/data/db

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    env_file: .env
    depends_on:
      - mongodb
    networks:
      - mynetwork
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$MONGODB_USER
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$MONGODB_PASSWORD
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=$MONGODB_USER
      - ME_CONFIG_BASICAUTH_PASSWORD=$MONGODB_PASSWORD
    ports:
      - "8081:8081"

networks:
  mynetwork:
    driver: bridge

volumes:
  db: